spring.application.name=api-gateway

server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=eventLedger
spring.cloud.gateway.routes[0].uri=lb://EVENTLEDGER
spring.cloud.gateway.routes[0].predicates[0]=Path=/events/**

spring.cloud.gateway.routes[1].id=accountService
spring.cloud.gateway.routes[1].uri=lb://ACCOUNTHANDLE
spring.cloud.gateway.routes[1].predicates[0]=Path=/accounts/**

management.endpoints.web.exposure.include=*
