# =====================================================
# Application
# =====================================================
spring.application.name=eventLedger
server.port=8080

# =====================================================
# MySQL Configuration
# =====================================================
spring.datasource.url=jdbc:mysql://localhost:3306/event_ledger_gateway
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =====================================================
# JPA Configuration
# =====================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =====================================================
# Eureka Client
# =====================================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# =====================================================
# Account Service
# =====================================================
account.service.url=http://localhost:8081

# =====================================================
# Spring Boot Actuator
# =====================================================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# =====================================================
# Logging
# =====================================================
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] %-5level %logger{36} - %msg%n
logging.level.root=INFO
logging.level.com.traceledger.gateway=DEBUG

# =====================================================
# Resilience4j Circuit Breaker
# =====================================================
resilience4j.circuitbreaker.instances.accountService.register-health-indicator=true
resilience4j.circuitbreaker.instances.accountService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.accountService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.accountService.sliding-window-size=10
resilience4j.circuitbreaker.instances.accountService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.accountService.permitted-number-of-calls-in-half-open-state=3

# =====================================================
# Retry
# =====================================================
resilience4j.retry.instances.accountService.max-attempts=3
resilience4j.retry.instances.accountService.wait-duration=2s